[app_specific]
interval_seconds = "30"
monitor_path = "/home/dwhitfield/Developer/GIT/Mitobyte"
project_path = "/home/dwhitfield/Developer/GIT/Mitobyte"
changes_needed = "2"
install_command = "npm --prefix /home/dwhitfield/Developer/GIT/Mitobyte install"
build_command = "npm --prefix /home/dwhitfield/Developer/GIT/Mitobyte run build"
run_command = "npm --prefix /home/dwhitfield/Developer/GIT/Mitobyte run start"
ignored_subdirs = [".git", "build", "next", "node", ".next", ".cache", "package-lock", "node_modules"]
